config/routes.rb
Itransition::Application.routes.draw do

  

  resources :galleries do
    resources :paintings 
  end
  
  get "store/index"
  get "store/about"
  get "store/search"
  devise_for :users
  post "markdown/preview"
 
  resources :chapers do
    resources :comments
    resources :parts
  end  
namespace :admin do
  get '/' => 'users#index'
  resources :users
end

  root 'store#index', as: 'store'

end

app/models/chaper.rb
class Chaper < ActiveRecord::Base
	belongs_to :user
	has_one :gallery, dependent: :destroy
	 attr_accessible :user_id, :title, :description
	 has_many :parts, dependent: :destroy
  validates :title, :description, presence: true ,uniqueness: true
  after_create :create_gallery
  has_many :comments, dependent: :destroy

  searchable do
    text :title, :boost => 5
    text :description
  end

  protected
  def create_gallery
  	gallery = Gallery.create(chaper_id:id,name:title)  	
  	self.gallery_id = gallery.id
  	self.save!
  end
end

app/controllers/chapers_controller.rb
class ChapersController < ApplicationController
  layout "chaper", only: [:show, :edit, :update]
  before_action :set_chaper, only: [:show, :edit, :update, :destroy]
  before_action :find_user, only: [:edit, :update, :destroy]
  skip_before_filter :authorize, only: [:edit, :update, :destroy, :index, :new, :create]
  load_and_authorize_resource
  # GET /chapers
  # GET /chapers.json
  def index

    @chapers = current_user.role_ids == [1] ? Chaper.all : Chaper.find_all_by_user_id(current_user.id)
  end

  # GET /chapers/1
  # GET /chapers/1.json
  def show
  end

  # GET /chapers/new
  def new
    @chaper = Chaper.new
  end

  # GET /chapers/1/edit
  def edit
  end

  # POST /chapers
  # POST /chapers.json
  def create
    @chaper = Chaper.new(chaper_params)
    @chaper.user_id = current_user.id 
    respond_to do |format|
      if @chaper.save

        format.html { redirect_to @chaper, notice: 'Chaper was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chaper }
      else
        format.html { render action: 'new' }
        format.json { render json: @chaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapers/1
  # PATCH/PUT /chapers/1.json
  def update
    respond_to do |format|
      if @chaper.update(chaper_params)
        format.html { redirect_to @chaper, notice: 'Chaper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapers/1
  # DELETE /chapers/1.json
  def destroy
    @chaper.destroy
    respond_to do |format|
      format.html { redirect_to chapers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chaper
      @chaper = Chaper.find(params[:id])
    end

     def find_user
      
      if !user_signed_in? || ((!current_user.admin?) && (current_user.id != @chaper.user_id))
        respond_to do |format|
        format.html { redirect_to @chaper, notice: 'ВЫ не имеее прав для выполнения этого действия' }
        format.json { render action: 'show', status: :created, location: @chaper }
      end
    end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chaper_params
      params.require(:chaper).permit(:title, :description, :user_id)
    end
end

app/helpers/chapers_helper.rb
module ChapersHelper
end

app/views/chapers/_form.html.erb
<%= form_for(@chaper) do |f| %>
  <% if @chaper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chaper.errors.count, "error") %> prohibited this chaper from being saved:</h2>

      <ul>
      <% @chaper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row collapse">
  <div class="small-1 columns">
    <%= f.label :title, class: "right inline" %>
  </div>
  <div class="small-11 columns"><%= f.text_field :title %></div>
</div>
<div class="row collapse">
  <div class="small-1 columns">
    <%= f.label :description, class: "right inline"%>
  </div>
  <div class="small-11 columns"><%= f.text_area :description %></div>
</div>
<div class="row collapse">
  <div class="small-11 small-offset-3 columns ",><%= f.submit class: "button radius"  %></div>
</div>

<% end %>

app/views/chapers/edit.html.erb
<h1>Editing chaper</h1>

<%= render 'form' %>

<%= link_to 'Show', @chaper %> |
<%= link_to 'Back', chapers_path %>

app/views/chapers/index.html.erb
<h1>Listing chapers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @chapers.each do |chaper| %>
      <tr>
        <td><%= chaper.title %></td>
        <td><%= truncate(strip_tags(markdown(chaper.description)), length: 200) %></td>
        <td><%= link_to 'Show', chaper %></td>
       
        <td><%= link_to 'Edit', edit_chaper_path(chaper) %></td>
        <td><%= link_to 'Destroy', chaper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
   
      </tr>
    <% end %>
  </tbody>
</table>

<br>
    <% if user_signed_in? %>
<%= link_to 'New Chaper', new_chaper_path, class: "button radius" %>
<%end%>

app/views/chapers/new.html.erb
<h1>New chaper</h1>

<%= render 'form' %>

<%= link_to 'Back', chapers_path %>

app/views/chapers/show.html.erb
<p id="notice"><%= notice %></p>

<h3><center>
  <%= @chaper.title %>
</center></h3>
 
<p>

  <%= markdown(@chaper.description) %>
</p>

 <% if @chaper.parts.count > 0%>
 <div class="panel callout radius">
  <h3>
    <strong><center><%= @chaper.parts.first.name %></center></strong>
    
  </h3>
 
  <p>
   
    <%= markdown(@chaper.parts.first.body) %>
  </p>
  </div>
<%end%>

 


<% if user_signed_in? && ((current_user.role_ids == [1] ) || (current_user.id == @chaper.user_id))%>
<%= link_to 'New Part', new_chaper_part_path(@part,  chaper_id: @chaper.id), class: "button radius" %>
 

<%= link_to 'Edit', edit_chaper_path(@chaper) , class: "button radius"%> 
<% end %>
<% if @chaper.parts.count > 1 %>
<%= link_to 'Next Part', chaper_part_path(id: "#{@chaper.parts.ids[1]}", chaper_id:params[:id]), class: "button radius" %>
<% end %>
<% if user_signed_in? %>
 <h2>Comments</h2>
<%= render @chaper.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
<% end %>