config/routes.rb
Itransition::Application.routes.draw do

  

  resources :galleries do
    resources :paintings 
  end
  
  get "store/index"
  get "store/about"
  get "store/search"
  devise_for :users
  post "markdown/preview"
 
  resources :chapers do
    resources :comments
    resources :parts
  end  
namespace :admin do
  get '/' => 'users#index'
  resources :users
end

  root 'store#index', as: 'store'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	belongs_to :chaper
	attr_accessible :name, :chaper_id
  has_many :paintings, dependent: :destroy
  
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]
before_action :find_user, only: [:edit, :update, :destroy]
  load_and_authorize_resource
  # GET /galleries
  # GET /galleries.json
  def index
    if current_user.role_ids == [1]
      @galleries =  Gallery.all  
    else  
      gallery_ids = Chaper.find_all_by_user_id(current_user.id).map{|x| x.gallery_id}
      @galleries = Gallery.find_all_by_id(gallery_ids)
    end  
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
 

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
 

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    if @gallery.update_attributes(params[:gallery])
      flash[:notice] = "Successfully updated gallery."
      redirect_to gallery_url
    else
      render :action => 'edit'
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
     @gallery.destroy
    flash[:notice] = "Successfully destroyed gallery."
    redirect_to galleries_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

def find_user
      
      if !user_signed_in? || ((current_user.role_ids != [1] ) && (current_user.id != @chaper.user_id))
        respond_to do |format|
        format.html { redirect_to @chaper, notice: 'ВЫ не имеее прав для выполнения этого действия' }
        format.json { render action: 'show', status: :created, location: @chaper }
      end
    end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name, :chaper_id)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery do |f| %>
  
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/galleries/edit.html.erb
<% title "Edit Gallery" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @gallery %> |
  <%= link_to "View All", galleries_path %>
</p>

app/views/galleries/index.html.erb
<% title "Galleries" %>

<% for gallery in @galleries %>
  <div class="gallery">
    <h2><%= link_to gallery.name, gallery %></h2>
    Paintings: <%= gallery.paintings.size %>
  </div>
<% end %>

app/views/galleries/show.html.erb
<% title @gallery.name %>
<h3><%= @gallery.name %></h3>
<% if @gallery.paintings.count > 0 %>
  <ul class="example-orbit-content" data-orbit>
    <% for painting in @gallery.paintings %>
    <li data-orbit-slide="headline-1">
      <div><center>
        <h2><%= painting.name %></h2>
        <% if painting.photo_file_name %>
        <%= image_tag painting.photo.url(:small)%>
        <% else %>
        <%= image_tag painting.photo_remote_url %>
        <% end %>
      </center>  
      </div>
    </li>
    <% end %>
  </ul>
<% end %>
</br>
</br>

<div class = "row">
  <% for painting in @gallery.paintings %>
  <div class="panel callout radius small-block-grid columns " >
    <div class="painting">
      <center>
      <% if painting.photo_file_name %>
      <%= image_tag painting.photo.url(:small)%>
      <% else %>
      <%= image_tag painting.photo_remote_url,  height: '300', width: '350' %>
      <% end %>
    </center>
      <div><center>
        <% if user_signed_in? && ((current_user.role_ids == [1] ) || (current_user.id == @gallery.chaper.user_id))%>
          <div class="name"><%= painting.name %></div>
          <div class="actions">
            <%= link_to "edit", edit_gallery_painting_path(painting.id, gallery_id:@gallery.id) %> |
            <%= link_to "remove", gallery_painting_path(painting.id, gallery_id:@gallery.id), :confirm => 'Are you sure?', :method => :delete %>
          </div>
        <% end %>
      </center>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class= "row">
<center>
<% if user_signed_in? && ((current_user.role_ids == [1] ) || (current_user.id == @gallery.chaper.user_id))%>
  <div class=" small-4 columns ">
    <%= link_to "Add a Painting", new_gallery_painting_path(:gallery_id => @gallery) ,class: "button radius"%> 
  </div>
  <div class=" small-4 columns ">  
    <%= link_to "Remove Gallery", @gallery, :confirm => 'Are you sure?', :method => :delete ,class: "button radius"%>
  </div>
  <div class=" small-4 columns ">
    <%= link_to "View Galleries", galleries_path, class: "button radius"%>
  </div>
<% end %>
</center>
</div>