config/routes.rb
Itransition::Application.routes.draw do

  

  resources :galleries do
    resources :paintings 
  end
  
  get "store/index"
  get "store/about"
  get "store/search"
  devise_for :users
  post "markdown/preview"
 
  resources :chapers do
    resources :comments
    resources :parts
  end  
namespace :admin do
  get '/' => 'users#index'
  resources :users
end

  root 'store#index', as: 'store'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        # attr_accessible :user_name
  has_and_belongs_to_many :roles
   before_save :setup_role
   has_many :chapers
attr_accessible :email, :password, :password_confirmation, :user_name, :block
  def role?(role)
      return !!self.roles.find_by_name(role.to_s)
  end

  # Default role is "users"
  def setup_role 
    if self.role_ids.empty?     
      self.role_ids = [2] 
    end
  end

  def admin?
    self.role_ids.include?(1)
  end
end
#a.kazeko@itransition.com

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        
        format.html { redirect_to admin_users_path, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else

        format.html { render :action => "new"}
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
    end
 
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_path, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :ok }
    end
  end
  def user_params
      params.require(:user).permit(:password, :password_confirmation, :email, :block)
    end
end

app/controllers/user_controller.rb
class UserController < Devise
	def user_params
      params.require(:user).permit(:user_name, :role_ids, :block)
  end
   before_save :setup_role, :setup_block

  def role?(role)
      return !!self.roles.find_by_name(role.to_s.camelize)
  end

  # Default role is "Registered"
  def setup_role 
    if self.role_ids.empty?     
      self.role_ids = [2] 
    end
  end

  def setup_block
    if self.block.empty?     
      self.block = false 
    end
  end
end

app/views/admin/users/_form.html.erb
<div class="control-group">
   <%= f.label :email, t("activerecord.attributes.user.email", :default => "Email"), :class => 'control-label' %>
  <div class="input">
    <%= f.text_field :email, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
   <%= f.label :password, t("activerecord.attributes.user.password", :default => "password"), :class => 'control-label' %>
  <div class="input">
    <%= f.password_field :password, :class => 'password_field' %>
  </div>
</div>
<div class="control-group">
   <%= f.label :Password, t("activerecord.attributes.user.password_confirmation", :default => "password_confirmation"), :class => 'control-label' %>
  <div class="input">
    <%= f.password_field :password_confirmation, :class => 'password_field' %>
  </div>
</div>

<div class="control-group">
   <%= f.label :block, t("activerecord.attributes.user.block", :default => "Block"), :class => 'control-label' %>
  <div class="input">
    <%= f.check_box :block %> 
  </div>
</div>

<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", admin_users_path %>
</div>

app/views/admin/users/edit.html.erb
<%= form_for [:admin, @user], :url => admin_user_path(@user), :html => { :class => "form-horizontal", :id => "edit_user" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/admin/users/index.html.erb
<h1>Users</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>ID</th>
        <th>
      <%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>
    </th>
        <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| -%>
   <tr>
    <td><%= user.id %></td>
        <td><%= link_to user.email, admin_user_path(user) %>
    </td>
        <td><%= user.created_at %></td>
    <td>
      <%= link_to "Show", admin_user_path(user) %>
      <%= link_to "Edit", edit_admin_user_path(user) %>
      <%= link_to "Destroy", admin_user_path(user), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

<%= link_to "New", new_admin_user_path, :class => 'btn btn-primary' %>

app/views/admin/users/new.html.erb
<%= form_for [:admin, @user], :url => admin_users_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/admin/users/show.html.erb
<label class="label"><%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>:</label>
<p><%= @user.email %></p>

<div class="form-actions">
<%= link_to "Back", admin_users_path, :class => 'btn'  %>
<%= link_to "Edit", edit_admin_user_path(@user), :class => 'btn' %>
<%= link_to "Delete", admin_user_path(@user), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>