config/routes.rb
Itransition::Application.routes.draw do

  

  resources :galleries do
    resources :paintings 
  end
  
  get "store/index"
  get "store/about"
  get "store/search"
  devise_for :users
  post "markdown/preview"
 
  resources :chapers do
    resources :comments
    resources :parts
  end  
namespace :admin do
  get '/' => 'users#index'
  resources :users
end

  root 'store#index', as: 'store'

end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Awesome Store", store_path %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="has-form">
        <div class="row collapse">
          <%= form_tag store_search_path, :method => :get do %>
          <div class="large-8 small-9 columns">
            <%= text_field_tag :search, params[:search], placeholder: "Find Stuff" %>
          </div>
          <div class="large-4 small-3 columns">
            <%= submit_tag "Search", :title => nil, class: "alert button expand" %>
          </div>
          <% end %>
        </div>
      </li>
      <li><%= link_to "About us", store_about_path %></li>
      <% if user_signed_in? %>
      <% if current_user.role_ids == [1]%>
          <li><%= link_to "Admin", admin_users_path %></li>
        <% end %>
        <li><%= link_to "My gallery", galleries_path %></li>
       <li><%= link_to "My chapers", chapers_path %></li>
  <li><%= link_to("My Profile", edit_user_registration_path)%></li>
  <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>  </li>

  <% else %>
  <li><%= link_to('Login', new_user_session_path) %>  </li>
<%end%>
    </ul>
  </section>
</nav>

   <div class="row">
   <div class="large-8 columns">
      
    <%= yield %>
  </div>
  <div class="large-4 columns">
    <h2 class="subheader">About Us</h2>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>
 
</div>    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "jquery" %>
    <%= csrf_meta_tags %>
     <%= yield(:head) %>
  </head>

  <body>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Awesome Store", store_path %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="has-form">
        <div class="row collapse">
          <%= form_tag store_search_path, :method => :get do %>
          <div class="large-8 small-9 columns">
            <%= text_field_tag :search, params[:search], placeholder: "Find Stuff" %>
          </div>
          <div class="large-4 small-3 columns">
            <%= submit_tag "Search", :title => nil, class: "alert button expand" %>
          </div>
          <% end %>
        </div>
      </li>
       <li><%= link_to "About us", store_about_path %></li>
      <% if user_signed_in? %>
        <% if current_user.role_ids == [1]%>
          <li><%= link_to "Admin", admin_users_path %></li>
        <% end %>
          <li><%= link_to "My gallery", galleries_path %></li>
          <li><%= link_to "My chapers", chapers_path %></li>
          <li><%= link_to("My Profile", edit_user_registration_path)%></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>  </li>
      <% else %>
        <li><%= link_to('Login', new_user_session_path) %>  </li>
      <%end%>
    </ul>
  </section>
</nav>

   <div class="row">
    <div class="large-3 columns">
    <h2 class="subheader">Заполнитель</h2>
    Вполне себе читалка
  </div>
   <div class="large-9 columns">
      
    <%= yield %>
  </div>
  
 
</div>   
 <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/chaper.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
 
    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
 
    <%= stylesheet_link_tag    "application" %>
 
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "vendor/custom.modernizr"%>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  </head>

  <body>

<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Awesome Store", store_path %></a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <li class="has-form">
        <div class="row collapse">
          <%= form_tag store_search_path, :method => :get do %>
          <div class="large-8 small-9 columns">
            <%= text_field_tag :search, params[:search], placeholder: "Find Stuff" %>
          </div>
          <div class="large-4 small-3 columns">
            <%= submit_tag "Search", :title => nil, class: "alert button expand" %>
          </div>
          <% end %>
        </div>
      </li>
      <li><%= link_to "About us", store_about_path %></li>
      <% if user_signed_in? %>
      <% if current_user.role_ids == [1]%>
          <li><%= link_to "Admin", admin_users_path %></li>
        <% end %>
        <li><%= link_to "My gallery", galleries_path %></li>
       <li><%= link_to "My chapers", chapers_path %></li>
  <li><%= link_to("My Profile", edit_user_registration_path)%></li>
  <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>  </li>

  <% else %>
  <li><%= link_to('Login', new_user_session_path) %>  </li>
<%end%>
    </ul>
  </section>
</nav>
   <div class="row" >
    <div class="large-2 columns">
    <h2 class="subheader">Parts</h2>
    <ul class="side-nav">
    
    <% @chaper.parts.each do |part| %>  
 
    <li><%= link_to "#{part.name}", chaper_part_path(part.id, chaper_id:@chaper.id)  %> </li> 
    <% end %>
    <%= link_to "Go to gallery", gallery_path(id: @chaper.gallery_id), class: "button radius sm" %>  
    </ul>
  </div>
   <div class="large-10 columns">
      
    <%= yield %>

  </div>
  
 
</div>    <%= javascript_include_tag "application" %>

  </body>
</html>